services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            DB_CONNECTION: mysql
            DB_HOST: 'mysql.railway.internal'   # Host của MySQL trên Railway
            DB_PORT: '3306'
            DB_DATABASE: '${DB_DATABASE}'      # Tên cơ sở dữ liệu trên Railway
            DB_USERNAME: '${DB_USERNAME}'      # Tên người dùng MySQL
            DB_PASSWORD: '${DB_PASSWORD}'      # Mật khẩu MySQL
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            # Không cần MySQL nữa, bỏ mysql ở đây
        command: >
            bash -c "php artisan migrate --force && php-fpm"
